// ESLint flat config, replacing the .eslintrc.cjs classic config. ESLint 9
// dropped eslintrc as the default and 10 removed the `--ext` flag outright, so
// the file selection that used to live in the lint script (`--ext ts,tsx`) is
// now part of the config and `npm run lint` is just `eslint .`.
//
// Rule set is unchanged: eslint:recommended + typescript-eslint recommended +
// react-hooks recommended, with the same react-refresh rule and the same two
// exceptions as before.
import js from '@eslint/js'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  // A config object with only `ignores` sets them globally -- the flat-config
  // equivalent of the old top-level ignorePatterns. `.eslintrc.cjs` was in that
  // list because CommonJS in an ESM package cannot be parsed; this file is ESM,
  // so it needs no such exemption and is linted like everything else.
  {
    ignores: ['dist', 'node_modules', 'playwright-report', 'test-results'],
  },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      // react-hooks 7 exposes both config styles and the names collide: the
      // top-level configs.recommended / configs['recommended-latest'] are still
      // eslintrc-shaped (plugins as an array of strings, which flat config
      // rejects outright). The flat equivalents live under configs.flat.
      reactHooks.configs.flat['recommended-latest'],
    ],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    linterOptions: {
      // Was --report-unused-disable-directives on the lint script. The flag is
      // superseded by this option, which is why the script no longer passes it.
      reportUnusedDisableDirectives: 'error',
    },
    plugins: { 'react-refresh': reactRefresh },
    rules: {
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
    },
  },
  // Browser globals belong to application source only. The old config set them
  // globally and then switched them off again per-override; flat config merges
  // languageOptions.globals across every matching entry rather than replacing
  // them, so scoping them here is what actually keeps `document` from being
  // considered defined inside a Playwright spec.
  {
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: { globals: globals.browser },
  },
  // Playwright specs and the Vite/Playwright configs run in Node.
  {
    files: ['tests/**/*.ts', '*.config.ts'],
    languageOptions: { globals: globals.node },
  },
  // Generated by the shadcn/ui CLI (see components.json). Upstream ships a
  // component and its cva variants from one file; reshaping vendored files to
  // satisfy a fast-refresh hint would only make future regeneration conflict.
  {
    files: ['src/components/ui/**'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },
)
